name: Auto approve
on:
  pull_request:
    types: [opened]


jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v5
      with:
        # Anything other than stuff in dev
        PATTERNS: |
          **/*
          !dev/**/*
    - uses: hmarr/auto-approve-action@v2.1.0
      if: ${{ ! env.GIT_DIFF }}
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
